/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package core.view;

import core.AppContext;
import core.controller.Response;
import core.model.entities.Appointment;
import core.model.entities.Doctor;
import core.model.entities.Hospitalization;
import core.model.entities.Patient;
import core.model.entities.User;
import core.model.enums.Specialty;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class AdminView extends javax.swing.JFrame {

    private final AppContext context = AppContext.getInstance();
    private int x, y;
    private ArrayList<User> users;
    private ArrayList<Appointment>appointments;
    private ArrayList<Hospitalization>hospitalizations;
    private User user;
    public AdminView(User user, ArrayList<User>users,ArrayList<Hospitalization> hospitalizations, ArrayList<Appointment> appointments) {
        initComponents();
        this.user = user;
        this.users = users;
        this.hospitalizations = hospitalizations;
        this.appointments = appointments;
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
        loadUserCombos();
    }

    private void loadUserCombos() {
        doctorSelectorComboBox.removeAllItems();
        patientSelectorComboBox.removeAllItems();
        doctorSelectorComboBox.addItem("Select one");
        patientSelectorComboBox.addItem("Select one");
        for (Doctor doctor : context.getUserRepository().getDoctors()) {
            doctorSelectorComboBox.addItem(String.valueOf(doctor.getId()));
        }
        for (Patient patient : context.getUserRepository().getPatients()) {
            patientSelectorComboBox.addItem(String.valueOf(patient.getId()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        adminTitleLabel = new javax.swing.JLabel();
        doctorRegisterPanel = new javax.swing.JPanel();
        openDoctorViewButton = new javax.swing.JButton();
        openPatientViewButton = new javax.swing.JButton();
        doctorFirstnameLabel = new javax.swing.JLabel();
        doctorFirstnameField = new javax.swing.JTextField();
        doctorLastnameLabel = new javax.swing.JLabel();
        doctorLastnameField = new javax.swing.JTextField();
        doctorIdLabel = new javax.swing.JLabel();
        doctorIdField = new javax.swing.JTextField();
        doctorSpecialtyLabel = new javax.swing.JLabel();
        doctorLicenseLabel = new javax.swing.JLabel();
        doctorLicenseField = new javax.swing.JTextField();
        doctorOfficeLabel = new javax.swing.JLabel();
        doctorOfficeField = new javax.swing.JTextField();
        doctorUsernameLabel = new javax.swing.JLabel();
        doctorUsernameField = new javax.swing.JTextField();
        doctorPasswordLabel = new javax.swing.JLabel();
        doctorPasswordField = new javax.swing.JTextField();
        doctorPasswordConfirmLabel = new javax.swing.JLabel();
        doctorPasswordConfirmField = new javax.swing.JTextField();
        doctorSpecialtyComboBox = new javax.swing.JComboBox<>();
        saveDoctorButton = new javax.swing.JButton();
        doctorFormSeparator = new javax.swing.JSeparator();
        doctorSelectorComboBox = new javax.swing.JComboBox<>();
        doctorSelectorLabel = new javax.swing.JLabel();
        patientSelectorLabel = new javax.swing.JLabel();
        patientSelectorComboBox = new javax.swing.JComboBox<>();
        navigationSeparator = new javax.swing.JSeparator();
        logoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        headerPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelRound2MouseDragged(evt);
            }
        });
        headerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound2MousePressed(evt);
            }
        });

        closeButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        closeButton.setText("X");
        closeButton.setBorderPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        closeButton.setFocusable(false);
        closeButton.setRequestFocusEnabled(false);
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        adminTitleLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        adminTitleLabel.setText("ADMIN VIEW");

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(adminTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addGap(19, 19, 19))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adminTitleLabel))
        );

        openDoctorViewButton.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        openDoctorViewButton.setText("DOCTOR VIEW");
        openDoctorViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openDoctorViewButtonActionPerformed(evt);
            }
        });

        openPatientViewButton.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        openPatientViewButton.setText("PATIENT VIEW");
        openPatientViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openPatientViewButtonActionPerformed(evt);
            }
        });

        doctorFirstnameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorFirstnameLabel.setText("Firstname");

        doctorFirstnameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doctorLastnameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorLastnameLabel.setText("Lastname");

        doctorLastnameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doctorIdLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorIdLabel.setText("ID");

        doctorIdField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doctorSpecialtyLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorSpecialtyLabel.setText("Specialty");

        doctorLicenseLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorLicenseLabel.setText("License Number");

        doctorLicenseField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doctorOfficeLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorOfficeLabel.setText("Assigned office");

        doctorOfficeField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doctorUsernameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorUsernameLabel.setText("User");

        doctorUsernameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doctorPasswordLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorPasswordLabel.setText("Password");

        doctorPasswordField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doctorPasswordConfirmLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorPasswordConfirmLabel.setText("Password confirmation");

        doctorPasswordConfirmField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doctorSpecialtyComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorSpecialtyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "General Medicine", "Cardiology", "Pediatrics", "Neurology", "Traumatology & Orthopedics", "Gynecology & Obstetrics", "Dermatology", "Psychiatry", "Oncology", "Ophthalmology", "Internal Medicine" }));

        saveDoctorButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        saveDoctorButton.setText("Save");
        saveDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDoctorButtonActionPerformed(evt);
            }
        });

        doctorFormSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        doctorSelectorComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorSelectorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        doctorSelectorLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorSelectorLabel.setText("Doctor");

        patientSelectorLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientSelectorLabel.setText("Patient");

        patientSelectorComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientSelectorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        navigationSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        logoutButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(doctorRegisterPanel);
        doctorRegisterPanel.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(saveDoctorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound3Layout.createSequentialGroup()
                                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(doctorFirstnameLabel)
                                    .addComponent(doctorSpecialtyLabel))
                                .addGap(18, 18, 18)
                                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelRound3Layout.createSequentialGroup()
                                        .addComponent(doctorSpecialtyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(doctorLicenseLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(doctorLicenseField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelRound3Layout.createSequentialGroup()
                                        .addComponent(doctorFirstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(doctorLastnameLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(doctorLastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(doctorIdLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(doctorIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelRound3Layout.createSequentialGroup()
                                .addComponent(doctorOfficeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(doctorOfficeField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRound3Layout.createSequentialGroup()
                                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelRound3Layout.createSequentialGroup()
                                        .addComponent(doctorUsernameLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(doctorUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelRound3Layout.createSequentialGroup()
                                        .addComponent(doctorPasswordLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(doctorPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelRound3Layout.createSequentialGroup()
                                        .addComponent(doctorPasswordConfirmLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(doctorPasswordConfirmField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(333, 333, 333)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(openDoctorViewButton)
                            .addGroup(panelRound3Layout.createSequentialGroup()
                                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelRound3Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(doctorSelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelRound3Layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(doctorSelectorLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutButton)
                        .addGap(318, 318, 318)))
                .addComponent(doctorFormSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(openPatientViewButton)
                            .addGroup(panelRound3Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(patientSelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(patientSelectorLabel)))
                .addGap(88, 88, 88))
            .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                    .addContainerGap(707, Short.MAX_VALUE)
                    .addComponent(navigationSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(523, 523, 523)))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addComponent(doctorFormSeparator)
                .addContainerGap())
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorFirstnameLabel)
                    .addComponent(doctorFirstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorLastnameLabel)
                    .addComponent(doctorLastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorIdLabel)
                    .addComponent(doctorIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorSpecialtyLabel)
                    .addComponent(doctorSpecialtyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorLicenseLabel)
                    .addComponent(doctorLicenseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doctorOfficeLabel)
                    .addComponent(doctorOfficeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorUsernameLabel)
                            .addComponent(doctorUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPasswordLabel)
                            .addComponent(doctorPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPasswordConfirmLabel)
                            .addComponent(doctorPasswordConfirmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(doctorSelectorLabel)
                        .addGap(18, 18, 18)
                        .addComponent(doctorSelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(openDoctorViewButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(saveDoctorButton)
                .addGap(123, 123, 123)
                .addComponent(logoutButton)
                .addGap(38, 38, 38))
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(patientSelectorLabel)
                .addGap(18, 18, 18)
                .addComponent(patientSelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(openPatientViewButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRound3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(navigationSeparator)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(doctorRegisterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doctorRegisterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelRound2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panelRound2MousePressed

    private void panelRound2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelRound2MouseDragged

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void saveDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDoctorButtonActionPerformed
        Response response = context.getDoctorController().register(
                doctorIdField.getText(),
                doctorUsernameField.getText(),
                doctorFirstnameField.getText(),
                doctorLastnameField.getText(),
                doctorPasswordField.getText(),
                doctorPasswordConfirmField.getText(),
                doctorSpecialtyComboBox.getItemAt(doctorSpecialtyComboBox.getSelectedIndex()),
                doctorLicenseField.getText(),
                doctorOfficeField.getText());
        JOptionPane.showMessageDialog(this, response.getMessage());
        if (response.isOk()) {
            users = new ArrayList<>(context.getUserRepository().getAll());
            doctorFirstnameField.setText("");
            doctorLastnameField.setText("");
            doctorIdField.setText("");
            doctorLicenseField.setText("");
            doctorOfficeField.setText("");
            doctorUsernameField.setText("");
            doctorPasswordField.setText("");
            doctorPasswordConfirmField.setText("");
            doctorSpecialtyComboBox.setSelectedIndex(0);
            loadUserCombos();
        }
    }//GEN-LAST:event_saveDoctorButtonActionPerformed

    private void openDoctorViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openDoctorViewButtonActionPerformed
        String selectedDoctorId = doctorSelectorComboBox.getItemAt(doctorSelectorComboBox.getSelectedIndex());
        if ("Select one".equals(selectedDoctorId)) {
            JOptionPane.showMessageDialog(this, "Doctor is required.");
            return;
        }
        Doctor temp = context.getUserRepository().findById(Long.parseLong(selectedDoctorId))
                .filter(Doctor.class::isInstance)
                .map(Doctor.class::cast)
                .orElse(null);
        if (temp == null) {
            JOptionPane.showMessageDialog(this, "Doctor not found.");
            return;
        }
        DoctorView doctor = new DoctorView(user,temp, users, hospitalizations,appointments);
        this.setVisible(false);
        doctor.setVisible(true);
    }//GEN-LAST:event_openDoctorViewButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        
        LoginView login = new LoginView();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void openPatientViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openPatientViewButtonActionPerformed
        String selectedPatientId = patientSelectorComboBox.getItemAt(patientSelectorComboBox.getSelectedIndex());
        if ("Select one".equals(selectedPatientId)) {
            JOptionPane.showMessageDialog(this, "Patient is required.");
            return;
        }
        Patient temp = context.getUserRepository().findById(Long.parseLong(selectedPatientId))
                .filter(Patient.class::isInstance)
                .map(Patient.class::cast)
                .orElse(null);
        if (temp == null) {
            JOptionPane.showMessageDialog(this, "Patient not found.");
            return;
        }
        PatientView patient = new PatientView(user,temp,users,appointments,hospitalizations);
        this.setVisible(false);
        patient.setVisible(true);
    }//GEN-LAST:event_openPatientViewButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton openDoctorViewButton;
    private javax.swing.JButton openPatientViewButton;
    private javax.swing.JButton saveDoctorButton;
    private javax.swing.JComboBox<String> doctorSpecialtyComboBox;
    private javax.swing.JComboBox<String> doctorSelectorComboBox;
    private javax.swing.JComboBox<String> patientSelectorComboBox;
    private javax.swing.JLabel adminTitleLabel;
    private javax.swing.JLabel doctorUsernameLabel;
    private javax.swing.JLabel doctorPasswordLabel;
    private javax.swing.JLabel doctorPasswordConfirmLabel;
    private javax.swing.JLabel doctorSelectorLabel;
    private javax.swing.JLabel patientSelectorLabel;
    private javax.swing.JLabel doctorFirstnameLabel;
    private javax.swing.JLabel doctorLastnameLabel;
    private javax.swing.JLabel doctorIdLabel;
    private javax.swing.JLabel doctorSpecialtyLabel;
    private javax.swing.JLabel doctorLicenseLabel;
    private javax.swing.JLabel doctorOfficeLabel;
    private javax.swing.JSeparator doctorFormSeparator;
    private javax.swing.JSeparator navigationSeparator;
    private javax.swing.JTextField doctorPasswordConfirmField;
    private javax.swing.JTextField doctorFirstnameField;
    private javax.swing.JTextField doctorLastnameField;
    private javax.swing.JTextField doctorIdField;
    private javax.swing.JTextField doctorLicenseField;
    private javax.swing.JTextField doctorOfficeField;
    private javax.swing.JTextField doctorUsernameField;
    private javax.swing.JTextField doctorPasswordField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel doctorRegisterPanel;
    // End of variables declaration//GEN-END:variables
}
