/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package core.view;

import core.AppContext;
import core.controller.Response;
import core.model.entities.Administrator;
import core.model.entities.Appointment;
import core.model.entities.Doctor;
import core.model.entities.Hospitalization;
import core.model.entities.Patient;
import core.model.entities.Prescription;
import core.model.entities.User;
import core.model.enums.AppointmentStatus;
import core.model.enums.HospitalizationStatus;
import core.model.enums.RoomType;
import core.model.enums.Specialty;

import java.awt.Color;
import java.time.LocalDate;
import java.time.Month;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import org.json.JSONObject;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class LoginView extends javax.swing.JFrame {

    private final AppContext context = AppContext.getInstance();
    private int x, y;
    private ArrayList<User> users;
    private ArrayList<Hospitalization> hospitalizations;
    private ArrayList<Appointment> appointments;

    public LoginView() {
        initComponents();
        this.setTitle("Login");
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);

        this.users = new ArrayList<>(context.getUserRepository().getAll());
        this.appointments = new ArrayList<>(context.getAppointmentRepository().getAll());
        this.hospitalizations = new ArrayList<>(context.getHospitalizationRepository().getAll());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        authTabbedPane = new javax.swing.JTabbedPane();
        loginPanel = new javax.swing.JPanel();
        loginTitleLabel = new javax.swing.JLabel();
        loginUsernameField = new javax.swing.JTextField();
        loginUsernameLabel = new javax.swing.JLabel();
        loginPasswordField = new javax.swing.JTextField();
        loginPasswordLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        patientRegisterPanel = new javax.swing.JPanel();
        registerFirstnameLabel = new javax.swing.JLabel();
        registerFirstnameField = new javax.swing.JTextField();
        registerLastnameLabel = new javax.swing.JLabel();
        registerLastnameField = new javax.swing.JTextField();
        registerIdLabel = new javax.swing.JLabel();
        registerIdField = new javax.swing.JTextField();
        registerGenderLabel = new javax.swing.JLabel();
        registerPhoneLabel = new javax.swing.JLabel();
        registerPhoneField = new javax.swing.JTextField();
        registerEmailLabel = new javax.swing.JLabel();
        registerEmailField = new javax.swing.JTextField();
        registerUsernameLabel = new javax.swing.JLabel();
        registerUsernameField = new javax.swing.JTextField();
        registerPasswordField = new javax.swing.JTextField();
        registerPasswordLabel = new javax.swing.JLabel();
        registerPasswordConfirmLabel = new javax.swing.JLabel();
        registerPasswordConfirmField = new javax.swing.JTextField();
        registerGenderComboBox = new javax.swing.JComboBox<>();
        registerPatientButton = new javax.swing.JButton();
        registerAddressLabel = new javax.swing.JLabel();
        registerAddressField = new javax.swing.JTextField();
        registerBirthdateLabel = new javax.swing.JLabel();
        registerBirthdateField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        headerPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelRound2MouseDragged(evt);
            }
        });
        headerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound2MousePressed(evt);
            }
        });

        closeButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        closeButton.setText("X");
        closeButton.setBorderPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        closeButton.setFocusable(false);
        closeButton.setRequestFocusEnabled(false);
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addGap(19, 19, 19))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(closeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        loginTitleLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        loginTitleLabel.setText("LOGIN");

        loginUsernameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        loginUsernameField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        loginUsernameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        loginUsernameLabel.setText("USERNAME");

        loginPasswordField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        loginPasswordField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        loginPasswordLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        loginPasswordLabel.setText("PASSWORD");

        loginButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        loginButton.setText("ENTER");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap(475, Short.MAX_VALUE)
                .addComponent(loginTitleLabel)
                .addGap(481, 481, 481))
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loginPasswordLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(loginUsernameLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(loginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(loginUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(471, 471, 471)
                        .addComponent(loginButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(loginTitleLabel)
                .addGap(74, 74, 74)
                .addComponent(loginUsernameLabel)
                .addGap(18, 18, 18)
                .addComponent(loginUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginPasswordLabel)
                .addGap(18, 18, 18)
                .addComponent(loginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(loginButton)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        authTabbedPane.addTab("Login", loginPanel);

        registerFirstnameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerFirstnameLabel.setText("Firstname");

        registerFirstnameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        registerLastnameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerLastnameLabel.setText("Lastname");

        registerLastnameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        registerIdLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerIdLabel.setText("ID");

        registerIdField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        registerGenderLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerGenderLabel.setText("Gender");

        registerPhoneLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerPhoneLabel.setText("Phone");

        registerPhoneField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        registerEmailLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerEmailLabel.setText("Email");

        registerEmailField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        registerUsernameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerUsernameLabel.setText("User");

        registerUsernameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        registerPasswordField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        registerPasswordLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerPasswordLabel.setText("Password");

        registerPasswordConfirmLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerPasswordConfirmLabel.setText("Password confirmation");

        registerPasswordConfirmField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerPasswordConfirmField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        registerGenderComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Female", "Male" }));

        registerPatientButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerPatientButton.setText("Save");
        registerPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerPatientButtonActionPerformed(evt);
            }
        });

        registerAddressLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerAddressLabel.setText("Address");

        registerAddressField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        registerBirthdateLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        registerBirthdateLabel.setText("Birthdate");

        registerBirthdateField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(patientRegisterPanel);
        patientRegisterPanel.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(registerPasswordLabel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registerUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(473, 473, 473)
                        .addComponent(registerUsernameLabel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(registerPasswordConfirmField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addComponent(registerPatientButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(registerPasswordConfirmLabel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(registerBirthdateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(registerBirthdateField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(registerFirstnameLabel)
                                .addGap(34, 34, 34)
                                .addComponent(registerFirstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registerLastnameLabel)
                            .addComponent(registerAddressLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(registerLastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(registerIdLabel)
                                .addGap(30, 30, 30)
                                .addComponent(registerIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(registerGenderLabel)
                                .addGap(26, 26, 26)
                                .addComponent(registerGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(registerAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(registerPhoneLabel)
                                .addGap(18, 18, 18)
                                .addComponent(registerPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(registerEmailLabel)
                                .addGap(18, 18, 18)
                                .addComponent(registerEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerFirstnameLabel)
                    .addComponent(registerFirstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerLastnameLabel)
                    .addComponent(registerLastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerIdLabel)
                    .addComponent(registerIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerGenderLabel)
                    .addComponent(registerGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(registerBirthdateLabel)
                        .addComponent(registerBirthdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(registerAddressLabel)
                        .addComponent(registerAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(registerPhoneLabel)
                        .addComponent(registerPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(registerEmailLabel)
                        .addComponent(registerEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(registerUsernameLabel)
                .addGap(18, 18, 18)
                .addComponent(registerUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerPasswordLabel)
                .addGap(18, 18, 18)
                .addComponent(registerPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registerPasswordConfirmLabel)
                .addGap(18, 18, 18)
                .addComponent(registerPasswordConfirmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(registerPatientButton)
                .addGap(42, 42, 42))
        );

        authTabbedPane.addTab("Patient register", patientRegisterPanel);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(authTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authTabbedPane)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelRound2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panelRound2MousePressed

    private void panelRound2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelRound2MouseDragged

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        Response response = context.getAuthController().login(loginUsernameField.getText(), loginPasswordField.getText());
        JOptionPane.showMessageDialog(this, response.getMessage());
        if (!response.isOk()) return;

        JSONObject data = (JSONObject) response.getData();
        long userId = data.getLong("id");
        User selectedUser = context.getUserRepository().findById(userId).orElse(null);
        if (selectedUser == null) return;

        this.users = new ArrayList<>(context.getUserRepository().getAll());
        this.appointments = new ArrayList<>(context.getAppointmentRepository().getAll());
        this.hospitalizations = new ArrayList<>(context.getHospitalizationRepository().getAll());

        if (selectedUser instanceof Administrator) {
            AdminView admin = new AdminView(selectedUser, users, hospitalizations, appointments);
            this.setVisible(false);
            admin.setVisible(true);
        } else if (selectedUser instanceof Doctor doctorUser) {
            DoctorView doctor = new DoctorView(selectedUser, doctorUser, users, hospitalizations, appointments);
            this.setVisible(false);
            doctor.setVisible(true);
        } else if (selectedUser instanceof Patient patientUser) {
            PatientView patient = new PatientView(selectedUser, patientUser, users, appointments, hospitalizations);
            this.setVisible(false);
            patient.setVisible(true);
        }

    }//GEN-LAST:event_loginButtonActionPerformed

    private void registerPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerPatientButtonActionPerformed
        String gender = registerGenderComboBox.getSelectedIndex() == 1 ? "Male"
                : registerGenderComboBox.getSelectedIndex() == 2 ? "Female" : "Select one";
        Response response = context.getPatientController().register(
                registerIdField.getText(),
                registerUsernameField.getText(),
                registerFirstnameField.getText(),
                registerLastnameField.getText(),
                registerPasswordField.getText(),
                registerPasswordConfirmField.getText(),
                registerEmailField.getText(),
                registerBirthdateField.getText(),
                gender,
                registerPhoneField.getText(),
                registerAddressField.getText());
        JOptionPane.showMessageDialog(this, response.getMessage());
        if (response.isOk()) {
            users = new ArrayList<>(context.getUserRepository().getAll());
            registerFirstnameField.setText("");
            registerLastnameField.setText("");
            registerIdField.setText("");
            registerPhoneField.setText("");
            registerEmailField.setText("");
            registerUsernameField.setText("");
            registerPasswordField.setText("");
            registerPasswordConfirmField.setText("");
            registerAddressField.setText("");
            registerBirthdateField.setText("");
            registerGenderComboBox.setSelectedIndex(0);
        }
        
    }//GEN-LAST:event_registerPatientButtonActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton registerPatientButton;
    private javax.swing.JComboBox<String> registerGenderComboBox;
    private javax.swing.JLabel loginTitleLabel;
    private javax.swing.JLabel registerUsernameLabel;
    private javax.swing.JLabel registerPasswordLabel;
    private javax.swing.JLabel registerPasswordConfirmLabel;
    private javax.swing.JLabel registerAddressLabel;
    private javax.swing.JLabel registerBirthdateLabel;
    private javax.swing.JLabel loginUsernameLabel;
    private javax.swing.JLabel loginPasswordLabel;
    private javax.swing.JLabel registerFirstnameLabel;
    private javax.swing.JLabel registerLastnameLabel;
    private javax.swing.JLabel registerIdLabel;
    private javax.swing.JLabel registerGenderLabel;
    private javax.swing.JLabel registerPhoneLabel;
    private javax.swing.JLabel registerEmailLabel;
    private javax.swing.JPanel patientRegisterPanel;
    private javax.swing.JTabbedPane authTabbedPane;
    private javax.swing.JTextField loginUsernameField;
    private javax.swing.JTextField registerPasswordConfirmField;
    private javax.swing.JTextField registerAddressField;
    private javax.swing.JTextField registerBirthdateField;
    private javax.swing.JTextField loginPasswordField;
    private javax.swing.JTextField registerFirstnameField;
    private javax.swing.JTextField registerLastnameField;
    private javax.swing.JTextField registerIdField;
    private javax.swing.JTextField registerPhoneField;
    private javax.swing.JTextField registerEmailField;
    private javax.swing.JTextField registerUsernameField;
    private javax.swing.JTextField registerPasswordField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel loginPanel;
    // End of variables declaration//GEN-END:variables
}
